### ISSUE TITLE
子タスク1: 論理名カラム機能の設定オプション追加

### ISSUE THREAD

**Issue by NTTAT-Higuchi-Hiroyuki** [NTTAT-Higuchi-Hiroyuki/tbls#2]
# 子タスク1: 設定オプションの追加

## 概要
論理名カラム機能の基盤となる設定オプションをtblsの設定システムに追加する。

## 作業内容
- `config/config.go`に新しい設定構造体を追加
- 論理名機能の有効/無効切り替え
- 区切り文字のカスタマイズ設定
- フォールバック動作の設定

## 設定例
```yaml
format:
  logicalName:
    enabled: true
    delimiter: "|"
    fallbackToName: true
```

## 成果物
- 設定オプションの実装
- 設定の読み込み・検証機能
- デフォルト値の設定

## 依存関係
なし（基盤となる機能）

## 工数見積もり
小（1-2日）
